config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get 'users/edit'
  get 'users/update'
  get '/users/editing', to: 'pages#edit_profile', as: 'edit_profile'
  get '/users/:id', to: 'pages#profile', as: 'user_profile'

  resources :users, only: [:edit, :update]

# extra route for deleting a dream in order to get a prefix
  delete 'dreams/:id', to: 'dreams#destroy', as: 'delete_dream'

# booking routes are nested in a dream
  resources :dreams, except: [:destroy] do
    resources :bookings
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :dream
end

app/models/dream.rb
class Dream < ApplicationRecord
  include PgSearch::Model
  mount_uploader :photo, PhotoUploader

  VIBES = ['Careless', 'Emotional', 'Empowering', 'Floating', 'Fun', 'Futuristic', 'Happy', 'Healing', 'Light', 'Loving', 'Optimistic', 'Past', 'Psychedelic', 'Realistic', 'Sexual', 'Stoned', 'Vibrant']

  has_many :bookings, dependent: :destroy
  belongs_to :user

  validates :title, presence: true, uniqueness: true
  validates :description, presence: true, uniqueness: true
  validates :duration, presence: true
  validates :vibe, inclusion: { in: VIBES, message:"please choose from the list" }

  pg_search_scope :search_by_vibe, against: :vibe
end

app/models/user.rb
class User < ApplicationRecord
  has_many :dreams
  has_many :bookings
  mount_uploader :photo, PhotoUploader

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    set_dream
    authorize @dream
    @booking = Booking.new
    authorize @booking
  end

  def create
    set_dream
    authorize @dream
    @booking = Booking.new(booking_params)
    authorize @booking
    set_user
    @booking.user = @user
    @booking.dream = @dream
    if @booking.save
      redirect_to user_profile_path(@user)
    else
      render :new
    end
  end

  def edit
    @dream = Dream.find(params[:dream_id])
    @booking = Booking.find_by dream_id: @dream
    authorize @booking
  end

  def update
    @dream = Dream.find(params[:dream_id])
    set_booking
    authorize @booking
    set_user
    @booking.user = @user
    @booking.dream = @dream
    @booking.update(booking_params)
    redirect_to user_profile_path(@user)
  end

  def destroy
    set_dream
    set_booking
    authorize @booking
    set_user
    @booking.destroy
    redirect_to user_profile_path(@user)
  end

  private

  def booking_params
    params.require(:booking).permit(:date_booking)
  end

  def set_dream
    @dream = Dream.find(params[:dream_id])
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def set_user
    @user = current_user
  end
end

app/controllers/dreams_controller.rb
class DreamsController < ApplicationController
  before_action :authenticate_user!
  def index
    # if params[:query].present?
    #   @dreams = Dream.search_by_vibe(params[:query])
    # else
    #   @dreams = policy_scope(Dream)
    # end
    @dreams = Dream.first

    # @dreams = Dream.search_by_vibe('Fun')
  end

  def show
    set_dream
    authorize @dream
    @booking = Booking.find_by dream_id: @dream
  end

  def new
    @dream = Dream.new
    authorize @dream
  end

  def create
    @dream = Dream.new(dream_params)
    @dream.user = current_user
    authorize @dream
    if @dream.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    set_dream
    authorize @dream
  end

  def update
    set_dream
    @dream.update(dream_params)
    authorize @dream
    @dream.save
    redirect_to dream_path(@dream)
  end

  def destroy
    set_dream
    authorize @dream
    @dream.destroy
    redirect_to root_path
  end

  private

  def dream_params
    params.require(:dream).permit(:title, :description, :duration, :vibe, :photo)
  end

  def set_dream
    @dream = Dream.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    if params[:query].present?
      @dreams = Dream.search_by_vibe(params[:query])
    else
      @dreams = policy_scope(Dream)
    end
  end

  def profile
    @user = User.find(params[:id])
    @dreams = @user.dreams
  end

  def edit_profile
    @user = current_user
    @dreams = @user.dreams
  end

  def edit_update
    @user = params[:photo]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    authorize @user
    @user.save
    redirect_to user_profile_path
  end

  private

  def user_params
    params.require(:user).permit(:photo, :nickname)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<div class="container">
  <div class="form-design">
    <%= simple_form_for [@dream, @booking] do |f| %>
      <h1>Change your booking for <strong><%= @dream.title %></strong> now!</h1>
      <%= f.input :date_booking, as: :string, required: false, input_html: {class: "datepicker"} %>
      <%= f.submit "UPDATE BOOKING", class: 'create-button-form' %>
    <% end %>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container">
  <div class="form-design">
    <%= simple_form_for [@dream, @booking], method: "post", id:"new-dream-form" do |f| %>
      <h1>Book <strong><%= @dream.title %></strong> now!</h1>
      <%= f.input :date_booking, as: :string, required: false, input_html: {class: "datepicker"} %>
      <%= f.submit "BOOK NOW", class: 'create-button-form' %>
    <% end %>
  </div>
</div>

app/views/dreams/edit.html.erb
<div class="container">
  <div class="form-design">
    <%= simple_form_for(@dream) do |f| %>
    <div class="typewriter">
      <h1 class="typewriter-text">DREAMERS,</h1>
    </div>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :vibe, collection: Dream::VIBES%>
    <%= f.input :duration, label:'Duration (min)', placeholder: 'forever' %>
    <%= f.input :photo, class: 'text' %>
    <%= f.input :photo_cache, as: :hidden, class: 'text'%>
    <%= f.submit 'UPDATE', class: 'create-button' %>
    <% end %>
  </div>
</div>

app/views/dreams/new.html.erb
<div class="container">
  <div class="form-design">
    <%= simple_form_for(@dream, :defaults => { :input_html => { :class => "text" } }) do |f| %>
    <div class="typewriter">
      <h1 class="typewriter-text">DREAMERS,</h1>
    </div>
    <%= f.input :title, class: 'text' %>
    <%= f.input :description, class: 'text' %>
    <%= f.input :vibe, collection: Dream::VIBES, class: 'text'%>
    <%= f.input :duration, label:'Duration (min)', placeholder: 'forever', class: 'text' %>
    <%= f.input :photo, class: 'text' %>
    <%= f.input :photo_cache, as: :hidden, class: 'text'%>
    <%= f.submit 'POST DREAM', class: 'create-button' %>
    <% end %>
  </div>
</div>

app/views/dreams/show.html.erb
<!--Dream show page with the details-->
<%# Banner %>

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0),rgba(0,0,0,0)), url(https://images.unsplash.com/photo-1514477917009-389c76a86b68?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1261&q=80
)">
</div>
<!-- Search function container -->

<h1 class="tagline">Curated Dreams catered<br>with care</h1>
 <!--  Search function container -->
<div class="container">
  <%= form_tag root_path, method: :get do %>
  <h3 class="vibe-text"><%= label :name, '' %></h3>
  <br><br>
  <% vibes_array = Dream::VIBES %>

  <%= select_tag :query,
      options_for_select(vibes_array), class: 'drop-down btn btn-flat'%>
       <%= submit_tag "Search", class: 'search-button btn btn-flat'%>
  <% end %>
</div>


<div class="main-comp">
  <h2 class="dream-title"><%= @dream.title %></h2>
  <span class="dot-dream"></span>
  <div class="dream-info">
  <p class="desc"><br>
      Duration: <%= @dream.duration %> mins<br>
      Vibe: <%= @dream.vibe %></p>
  <p>By <strong><%= link_to @dream.user.nickname, user_profile_path(@dream.user) %></strong></p>
</div>




    <%  if @dream.photo.present? %>
      <%= cl_image_tag @dream.photo, height:350, width: 600, crop: :fill, class: 'dream-image' %>
    <% else %>
<!-- standard picture -->
      <%= image_tag "http://getwallpapers.com/wallpaper/full/f/e/b/1156420-full-size-hd-gradient-wallpapers-2560x1440-free-download.jpg", alt: "alttext", height:350, width: 600, crop: :fill, class: 'standard-img' %>
    <% end %>
    <h5 style="text-align: center">Description: <%= @dream.description %></h3>

    <% if @dream.user != current_user%>
      <%= link_to 'DREAM THIS', new_dream_booking_path(@dream), height:350, width: 600, crop: :fill, class: 'book-button' %>
    <% end %>

  <!-- edit and delete button, only for dream creator or admin-->
    <div class="btns-flex">
      <% if policy(@dream).edit? %>
        <p class="edit-button current">Edit</p>
      <% end %>
      <% if policy(@dream).destroy? %>
        <p class="p-b"><%= link_to 'Delete', delete_dream_path, method: :delete, data: { confirm: "Delete #{@dream.title}?" }, class: 'delete-button' %></p>
    </div>
      <% end %>
    </div>

    <div class="edit-form">
      <%= simple_form_for(@dream) do |f| %>
      <h1>DREAMERS,</h1>
      <%= f.input :title %>
      <%= f.input :description %>
      <%= f.input :vibe, collection: Dream::VIBES%>
      <%= f.input :duration, label:'Duration (min)', placeholder: 'forever' %>
      <%= f.input :photo, class: 'text' %>
      <%= f.input :photo_cache, as: :hidden, class: 'text'%>
      <%= f.submit 'UPDATE DREAM', class: 'create-button-form' %>
      <% end %>
    </div>

    <div class="footer">
      <div class="footer-links">
        <a href="#"><i class="fab fa-github"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="#"><i class="fab fa-linkedin"></i></a>
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>D R E A M S</title>
    <link href="https://fonts.googleapis.com/css?family=Red+Hat+Text&display=swap" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <a class="navbar-brand" href="/">
        <h2>D R E A M S</h2>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

 <!--dropdown: if user session is active, it will show the avatar-->
 <!--else: it will show sign up/sign in options-->

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'POST A DREAM', new_dream_path , class: 'nav-link'  %>
          </li>
          <li class="nav-item dropdown">
            <% if current_user.photo.present? %>
              <%= cl_image_tag current_user.photo, class: 'avatar dropdown-toggle',
                  id:"navbarDropdown", data: {toggle:"dropdown"},
                  'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= cl_image_tag "whzexbgwqgsw5xgctrit", class: 'avatar dropdown-toggle',
                  id:"navbarDropdown", data: {toggle:"dropdown"},
                  'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
             <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <%= link_to 'Profile', user_profile_path(current_user), class: 'dropdown-item' %>
                <%= link_to 'Log out', destroy_user_session_path, class: 'dropdown-item', method: :delete, data: { confirm: "Are you ready to take a nap?" }  %>
              </div>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'SIGN UP', new_user_registration_path , class: 'nav-link'  %>
            </li>
            <li class="nav-item">
              <%= link_to 'LOG IN', new_user_session_path, class: 'nav-link'  %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>

    <%= yield %>
 <!--    <div class="footer">
      <div class="footer-links">
        <a href="https://film-grab.com/2013/11/13/the-big-lebowski/#bwg1497/93095">SNOOZE</a>
        <a href="https://film-grab.com/2015/10/20/back-to-the-future/#bwg571/35041">NAP</a>
        <a href="https://film-grab.com/2017/02/13/the-matrix/#bwg19/911">DEEP</a>
      </div>
    </div> -->

    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<%# Banner %>
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0),rgba(0,0,0,0)), url(https://images.unsplash.com/photo-1514477917009-389c76a86b68?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1261&q=80
)">
</div>
<!-- Search function container -->

<h1 class="tagline">Curated Dreams catered<br>with care</h1>
 <!--  Search function container -->
<div class="container">
  <%= form_tag root_path, method: :get do %>
  <h3 class="vibe-text"><%= label :name, '' %></h3>
  <br><br>
  <% vibes_array = Dream::VIBES %>

  <%= select_tag :query,
      options_for_select(vibes_array), class: 'drop-down btn btn-flat'%>
       <%= submit_tag "Search", class: 'search-button btn btn-flat'%>
  <% end %>
</div>


 <p class="intro">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been<br> the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley<br> of type and scrambled it to make a type specimen book. </p>



<div class="cards">

<%# Cards %>
<% if params[:query].present? %>
  <% @dreams.each do |dream| %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= dream.photo %>)">
      <%= link_to dream.title, dream_path(dream) %>
    </div>
  <% end %>
<% else %>
  <div class="cards">
    <% @dreams.each do |dream| %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= dream.photo %>)">
        <%= link_to dream.title, dream_path(dream) %>
      </div>
    <% end %>
  </div>
<% end %>
</div>

<!-- Back to all Dreams after a search -->


  <% link_to '*All dreams*', root_path, class: 'create-button' %>

<!--Button to add a new dream-->

<div style="text-align:center">
  <%= link_to 'Post your dream', new_dream_path, class: 'btn-flat' %>
</div>

  <div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
</div>

app/views/pages/profile.html.erb
<div class="container" id="user-dashboard">

  <div class="header">
  <% if @user.photo.present?  %>
    <%= cl_image_tag(@user.photo, width: 300, height: 300, crop: :thumb, gravity: :face, radius: :max, class: 'avatar-large')%>
  <% else %>
    <%= cl_image_tag("whzexbgwqgsw5xgctrit",
      width: 300, height: 300, crop: :fill, class: 'avatar-large') %>
  <% end %>
  <div class="header-text">
    <h1><%= @user.nickname %></h1>
    <% if @user == current_user %>
      <%= link_to 'Edit your profile', edit_user_path(@user) %>
    <% else %>
      <p>Discover the dreams of your friend!</p>
    <% end %>
  </div>
</div>

  <h3><strong><%= @user.nickname %>'s</strong> posted dreams:</h3>
<!--If the @user IS the current user (own profile)-->
  <% if @user == current_user %>
<!-- Go over @dreams (user.dreams) -->
      <% @dreams.each do |dream| %>
      <!--First column: display dream image-->
      <div class="own-dreams">
        <% url = "http://res.cloudinary.com/dl33w8wdg/#{dream.photo.identifier}" %>
        <%= image_tag(url) %>
        <div class="own-dreams-text">
          <h4><%= link_to dream.title, dream_path(dream) %></h4>
             <!--Second column: if bookings is empty, say there are no bookings-->
            <% if dream.bookings.empty? %>
              <h5>Whoops - this dream hasn't been booked yet.</h5>
            <!--If there are bookings, show the nickname of the bookers and stats-->
            <% else %>
              <% dream.bookings.each do |booking| %>
                <p>Booked by: <%= booking.user.nickname %>, on  <%= booking.created_at %>, for <%= booking.date_booking %></p>
              <% end %>
            <% end %>
          </div>
        </div>
      <% end %>

    <!--User's OWN bookings-->

    <h3><strong><%= @user.nickname %>'s</strong> booked dreams:</h3>
      <!--If Bookings are empty, say there are none-->
      <div class="own-booking">
       <% if @user.bookings.empty? %>
         <p>Whoops - I still haven't booked any dream :(</p>
      </div>
      <% else %>

      <!--else, show the user's OWN bookings & update/delete buttons-->
        <% @user.bookings.each do |booking| %>
         <div class="own-booking-present">
            <h4><%= link_to booking.dream.title, dream_path(booking.dream) %>, booked on <%= booking.date_booking  %></h4>
            <div class="action-booking">
              <%= link_to 'UPDATE', edit_dream_booking_path(booking.dream, booking), class: 'create-button' %>
              <%= link_to 'DELETE', dream_booking_path(booking.dream, booking),
                  method: :delete,
                  data: { confirm: "Are you sure?" },
                  class: 'create-button' %>
            </div>
          </div>
        <% end %>
      <% end %>




  <!--if @user is NOT!! the current user (someone else's profile)-->
  <% else %>

    <!--go over the dreams they posted-->
    <% @dreams.each do |dream| %>
      <div class="own-dreams">
      <!--First column: display dream image-->
        <% url = "http://res.cloudinary.com/dl33w8wdg/#{dream.photo.identifier}" %>
        <%= image_tag(url) %>
        <!--Second column: show title, description, vibe-->
        <div class="own-dreams-text">
          <h4><%= link_to dream.title, dream_path(dream) %></h4>
          <p><%= dream.description %></p>
          <h5>Vibe: <%= dream.vibe %></h5>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/shared/_profile_picture.htlm.erb
<%= simple_form_for(article) do |f| %>
  <!-- [...] -->
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <!-- [...] -->
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="form-design">
    <h1>Edit your profile</h1>
    <%= simple_form_for(@user) do |f| %>
    <%= f.input :nickname %>
    <%= f.input :photo, class: 'text' %>
    <%= f.input :photo_cache, as: :hidden, class: 'text'%>
    <%= f.submit "Save changes" %>
    <% end %>
  </div>
</div>